client-reputation-service:
  url: http://127.0.0.1:${wiremock.server.port}

delivery-cost-service:
  url: http://127.0.0.1:${wiremock.server.port}

special-price-catalogue-service:
  url: http://127.0.0.1:${wiremock.server.port}

spring:
  main:
    allow-bean-definition-overriding: true
